sudo: false
branches:
  only:
  - pelican
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_120135e51708_key -iv $encrypted_120135e51708_iv -in publish-key.enc -out publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IndentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin https://github.com/patcdaniel/patcdaniel.github.io.git
- git fetch origin -f master:master
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
  - make github